name: Run Postman API Tests

on:
  push:
    branches:
      - main  # Specify the branch to trigger tests on push
    paths:
      - 'postman/collections/Resources.json'  # Only trigger if APIs.json is modified
      - 'postman/collections/environment.json'  # Only trigger if environment.json is modified

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use a specific Node.js version

      # Step 3: Install Newman and HTML Reporter
      - name: Install Newman and HTML Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-html  # Install the HTML reporter for Newman

      # Step 4: Run Newman with Postman collection
      - name: Run API Tests
        run: |
          newman run postman/collections/Resources.json \
            --environment postman/collections/environment.json \
            --reporters cli,html \
            --reporter-html-export postman-results/report.html  # Generate HTML report

      # Step 5: Upload HTML report as artifact
      - name: Upload HTML Report to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: postman-results  # Upload the folder containing the HTML report
          
    
    # Step 6: Deploy the report to GitHub Pages
  deploy:
    needs: run-postman-tests
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages  # Use this for GitHub Pages deployment
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2


