name: Run Postman API Tests

on:
  push:
    branches:
      - main  # Replace with your branch name
    paths:
      - APIs.json  # Trigger when collection is updated
      - environment.json  # Trigger when environment is updated

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install Node.js and Newman
      - name: Install Node.js and Newman
        run: |
          sudo apt-get update
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install -g newman

      # Step 3: Run the Postman collection with environment variables
      - name: Run Postman Collection
        run: |
          newman run APIs.json \
            --environment environment.json \
            --reporters cli,junit \
            --reporter-junit-export results.xml

